---
- name: Create group
  group:
    name: "{{ node_exporter_group }}"
    system: yes

- name: Create user
  user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    system: yes
    shell: /usr/sbin/nologin

- name: Download node_exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"
    mode: "0644"

- name: Extract archive
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Copy binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_install_dir }}/node_exporter"
    mode: "0755"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    remote_src: yes

- name: Install systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0644"
  notify: Reload systemd

- name: Enable and start service
  service:
    name: node_exporter
    state: "{{ node_exporter_service_state }}"
    enabled: "{{ node_exporter_service_enabled }}"
